name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cloudflared
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Configure SSH
      run: |
        echo "Host mertalukas
          HostName ssh.mertalukas.cz
          User root
          ProxyCommand cloudflared access ssh --hostname %h --service-token-id ${{ secrets.CLOUDFLARE_SERVICE_TOKEN_ID }} --service-token-secret ${{ secrets.CLOUDFLARE_SERVICE_TOKEN_SECRET }}
        " >> ~/.ssh/config

    - name: Set up Docker Buildx
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use
        docker buildx inspect --bootstrap

    - name: Build Docker image
      run: |
        docker login -u lmerta -p ${{ secrets.DOCKER_PASSWORD }}
        docker buildx build --platform linux/arm/v7 -t lmerta/tws-kahoot:latest --push .

    - name: Deploy Docker image to Raspberry Pi
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no root@mertalukas "
          docker stop tws-kahoot-cont || true && docker rm tws-kahoot-cont || true
          docker rmi lmerta/tws-kahoot:latest || true
          docker pull lmerta/tws-kahoot:latest
          docker run -dp 6000:5200 --name tws-kahoot-cont --restart unless-stopped lmerta/tws-kahoot:latest
        "
